# Site settings
title: GraphStream - A Dynamic Graph Library
email: team@graphstream-project.org
description: >
  GraphStream, java library, API, Graph Visualisation, Graph Layout
baseurl: ""
url: "http://graphstream-project.org"
github_username:  graphstream
content_img: "/media/img/"
media: "/media"
api_modules: ['core', 'algo', 'ui']
news_count: 5

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-redirect-from
